### PR TITLE
Adding support for rOCCI-server v2

### PR DESCRIPTION
**Pull request by arax**
## Overview
* New flag `--rocci-remote-templates` for use with rOCCI-server v2
* Scoped pool info (no user-defined images or templates published)
* Added `--cloudkeeper-images` alias for `--vmcatcher-images`
* Minor adjustments in configuration samples
## Important
`--rocci-remote-templates` tells the provider to pull resource templates from OCA (OpenNebula's XML-RPC API), not from a local directory. This option is REQUIRED for deployments with rOCCI-server v2+.

### CODE REVIEW

**Comment by arax** [comment]
This PR still needs a bit of work. Mainly testing and code clean-up.

**Comment by gwarf** [comment]
Hi Boris,
Thanks, so this should be compatible with all the rOCCI server versions?
Best,
Baptiste

**Comment by arax** [comment]
Hi @gwarf ,
yes, it should be backwards compatible. With rOCCI-server < 2, no changes. For rOCC-server >= 2, use `--rocci-remote-templates` and `--rocci-template-dir` will be ignored.

**Comment by arax** [comment]
@gwarf Can we push this for release ASAP? It is a requirement for the upcoming rOCCI-server v2 stable release. If there is anything you need me to do, pls, let me know.

**Comment by gwarf** [comment]
LGTM. Thanks Boris! :+1:

**Pull request merged**
