### PR TITLE
tox.ini: fix bandit call

### PR DESCRIPTION
**Pull request by gwarf**
Fix copy/paste error.

### CODE REVIEW

**Comment by gwarf** [comment]
@arax this commits enables bandit testing and this did highlight some potential problems related to XML, fixing them requires to use defusedxml, some special XML libs patched to fix this, can you please check if it looks good for you?

**Comment by gwarf** [comment]
@alvarolopez you know a bit this defusedxml stuff? Should we go this way and add python-defusedxml as a package dependency? Or should we disable these tests?

**Comment by arax** [comment]
@gwarf As far as I can tell, it looks OK. I'm just not sure if we are using that correctly. Official documentation seems to mention something about `monkey_patch()` (see https://pypi.python.org/pypi/defusedxml#defusedxml-xmlrpc)

**Comment by gwarf** [comment]
@arax you are right, I pushed a commit to call monkey_patch().

**Comment by gwarf** [comment]
OK so at least now the code seems to work, but bandit always complains, it checks for the import but not that monkey_patch is called :/ So at the end we will have to disable this test explicitly with # nosec

**Comment by arax** [comment]
Maybe it checks for `defused.xmlrpc.monkey_patch()` explicitly and the shortened version confuses the analyzer.

**Comment by gwarf** [comment]
Looking at  https://github.com/openstack/bandit/blob/master/bandit/blacklists/imports.py I don't think it checks for anything. And in fact the defused namespace (instead of defusedxml) looks strange...

**Comment by arax** [comment]
Agreed, let's way a bit. Maybe @alvarolopez has some insight here.

**Comment by alvarolopez** [comment]
Yes, bandit only checks for the import, but calling monkey_patch() should protect the xmlrpc code from the attacks.

I would meld 41fc5ca, 10e8ebd and ab27ab7 into a single commit, and do the monkey patch right after the import with the `#nosec` label.

**Comment by gwarf** [comment]
@alvarolopez is it OK now? I can squash everything in one commit if you prefer.
Also on CentOS 7 python2-defusedxml is not in the default repositories and EPEL will have to be used.

**Comment by alvarolopez** [comment]
For me this is fine as it is right now

**Pull request merged**
