### PR TITLE
One template for storage

### PR DESCRIPTION
**Pull request by gwarf**
Hi,
Here is a PR to use only one template for the storage part, as it is already done for the compute part, so it will work in the same way and ease the work on the new Glue 2.1 support.
The compute_bdii.ldif template was also renamed to storage.ldif. (There are still a lot of unnecessary reference to bdii to be cleaned in the code).
Thanks!

### CODE REVIEW

**Comment by enolfc** [comment]
Hi Baptiste!

could you reorganise/rebase commits into a single one?

Cheers
Enol

**Comment by gwarf** [comment]
Sure, yes, I can. (not a big fan of squashing in fact).
I will check this ASAP.

**Comment by gwarf** [comment]
I need to push a couple of fixes for the storage template, wait before merging, thanks!

**Comment by gwarf** [comment]
Pushed and squashed (Dropping deprecated templates, and fixing two wrong variables' name in the storage.ldif template).

**Comment by alvarolopez** [comment]
Merged from here: https://github.com/EGI-FCTF/cloud-info-provider/pull/45

**Pull request closed without merging**
