### PR TITLE
Updated OpenNebula provider

### PR DESCRIPTION
**Pull request by arax**
* Using `cloudkeeper` attributes instead of vmcatcher ones
* Using `xmlrpclib` instead of raw `urllib` requests
* Code clean-up and refactoring

### CODE REVIEW

**Comment by arax** [comment]
@gwarf AFAIK, this is ready. Please, review and merge if you deem it acceptable.

**Comment by gwarf** [comment]
Thanks @arax it looks good!
It is probably just a detail but I still find a bit confusing to have OpenNebulaBaseProvider.get_images and OpenNebulaROCCIProvider.get_templates to be both working and returning a variable named templates, perhaps it would be better to use flavors or images somewhere or add some doc, what do you think?
(I'm looking at setting up a cloudkeeper/opennebula 5.2/cloud-info-provider testbed, but I've not yet finished...)

**Comment by arax** [comment]
@gwarf I will definitely add docs. I just needed feedback for the overall functionality and python-ness (I'm not a python developer) :-)

And yes, I hate the `images` <-> `templates` confusion as well. Unfortunately, cleaning this up wouldn't be easy. We would have to rename `get_templates` to `get_flavors` on all providers and separate IndigoON provider because it uses a completely different terminology and returns different things (`get_images` and `get_templates` actually make sense there). Basically, it would be a major refactoring/redesign job.

This definitely needs to be cleaned up, but I would bundle that discussion with the discussion about moving away from BDII.

**Comment by gwarf** [comment]
I'm not a python expert too, python-ness seem great AFAICT. :)
So I will merge then if you agree I can package it so that we can validated it and send it to AppDB and SR for CMD, as the last pre Glue 2.1 version probably.

**Comment by arax** [comment]
Should I add docs first? Or are you happy with the current lack of docu comments?

**Pull request merged**
